// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuuFGsexxGu66Y55jkkElrbSTVd_ZRNmA',
    appId: '1:135949381733:web:e00284496ae13df08c968c',
    messagingSenderId: '135949381733',
    projectId: 'fir-auth-6ea9e',
    authDomain: 'fir-auth-6ea9e.firebaseapp.com',
    storageBucket: 'fir-auth-6ea9e.firebasestorage.app',
    measurementId: 'G-YL1H3QE13J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65LTrGyHP3bvGrZquzWVt8bbWiwMkFpY',
    appId: '1:135949381733:android:9af1f25a487176d28c968c',
    messagingSenderId: '135949381733',
    projectId: 'fir-auth-6ea9e',
    storageBucket: 'fir-auth-6ea9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCeVVgkNYGRhddoLDKyQnTKYYG4VaJsIg',
    appId: '1:135949381733:ios:59663fcfba4fae118c968c',
    messagingSenderId: '135949381733',
    projectId: 'fir-auth-6ea9e',
    storageBucket: 'fir-auth-6ea9e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );
}
